services:
    - mongodb
    - rabbitmq # will start rabbitmq-server
    - --status-all; sudo rm -rf /tmp/; sudo service mysql
    - rabbitmq-server

install:
    - sudo apt-get install -y --force-yes apache2
